### ISSUE TITLE
Division structure: add department button broken

### ISSUE THREAD

**Issue by mshappe** [CON-In-A-Box/CIAB-Signin#292]
The little yellow plus sign spouts a javascript error in the console instead of doing what's needed to allow adding a department.

**Comment by AricStewart** [comment]
Should now be fixed.

**Comment by mshappe** [comment]
Possibly, but it's not yet deployed anywhere I can see it :-D

**Comment by AricStewart** [comment]
True, I have been closing bugs when things have been merged into the master branch, mostly because for a long time deliveries just where never happening.

Do we want to change that process?

**Comment by mshappe** [comment]
Lemme think about that. For now, continue as you have been. I guess the main point is that I need to stick Thomas with a pointy thing to get things deployed since they're still not autodeploying.
